version: '3'
services:
  cli:
    build: .
    image: keboola/syrup-cli
    volumes:
      - .:/code
    entrypoint: /code/bin/cli
    tty: true
    stdin_open: true
    environment:
      - KBC_STORAGE_TOKEN

  tests: &tests
    build: .
    image: keboola/syrup-cli
    entrypoint: /code/phpunit.sh
    tty: true
    stdin_open: true
    environment:
      - KBC_STORAGE_TOKEN
      - KBC_JOBRUNNER_COMPONENTID
      - KBC_JOBRUNNER_CONFIGURATIONID
      - KBC_JOBRUNNER_TAG

  dev:
    <<: *tests
    entrypoint: []
    command: bash
    volumes:
      - .:/code
